cluster.name: CLUSTER_NAME
script.inline: on
script.indexed: on
bootstrap.mlockall: true
node.data: false
network.publish_host: HOST_IP
discovery.zen.ping.multicast.enabled: false
discovery.type: ec2
discovery.ec2.ping_timeout: "30s"
cloud.aws.region: "us-east"
plugin.mandatory: "cloud-aws"